// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package apipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetFibonacciServiceClient is the client API for GetFibonacciService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetFibonacciServiceClient interface {
	GetFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (*FibonacciResponse, error)
}

type getFibonacciServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetFibonacciServiceClient(cc grpc.ClientConnInterface) GetFibonacciServiceClient {
	return &getFibonacciServiceClient{cc}
}

func (c *getFibonacciServiceClient) GetFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (*FibonacciResponse, error) {
	out := new(FibonacciResponse)
	err := c.cc.Invoke(ctx, "/api.GetFibonacciService/GetFibonacci", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetFibonacciServiceServer is the server API for GetFibonacciService service.
// All implementations must embed UnimplementedGetFibonacciServiceServer
// for forward compatibility
type GetFibonacciServiceServer interface {
	GetFibonacci(context.Context, *FibonacciRequest) (*FibonacciResponse, error)
	mustEmbedUnimplementedGetFibonacciServiceServer()
}

// UnimplementedGetFibonacciServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetFibonacciServiceServer struct {
}

func (UnimplementedGetFibonacciServiceServer) GetFibonacci(context.Context, *FibonacciRequest) (*FibonacciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFibonacci not implemented")
}
func (UnimplementedGetFibonacciServiceServer) mustEmbedUnimplementedGetFibonacciServiceServer() {}

// UnsafeGetFibonacciServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetFibonacciServiceServer will
// result in compilation errors.
type UnsafeGetFibonacciServiceServer interface {
	mustEmbedUnimplementedGetFibonacciServiceServer()
}

func RegisterGetFibonacciServiceServer(s grpc.ServiceRegistrar, srv GetFibonacciServiceServer) {
	s.RegisterService(&GetFibonacciService_ServiceDesc, srv)
}

func _GetFibonacciService_GetFibonacci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibonacciRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetFibonacciServiceServer).GetFibonacci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GetFibonacciService/GetFibonacci",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetFibonacciServiceServer).GetFibonacci(ctx, req.(*FibonacciRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetFibonacciService_ServiceDesc is the grpc.ServiceDesc for GetFibonacciService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetFibonacciService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.GetFibonacciService",
	HandlerType: (*GetFibonacciServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFibonacci",
			Handler:    _GetFibonacciService_GetFibonacci_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/fibonacci.proto",
}
